name: Deploy React App to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # ✅ FIX: run inside React project folder
      - name: Install Dependencies
        working-directory: ./React_Single_Page_Website
        run: npm install

      # ✅ FIX: build inside React project folder
      - name: Build Project
        working-directory: ./React_Single_Page_Website
        run: npm run build

      # Configure AWS using OIDC (BEST PRACTICE)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::654485376127:role/github-actions-role
          aws-region: ap-south-1

      # ✅ FIX: deploy correct build path
      - name: Upload to S3
        run: |
          aws s3 sync ./React_Single_Page_Website/build s3://bucket-for-npm-static-website --delete
